
-- quest 929
UPDATE locales_quest SET Title_loc3="Teldrassil: Die Verweigerung der Aspekte",Objectives_loc3="Füllt die Jadephiole.",OfferRewardText_loc3="Es ist nur natürlich, dass unser Volk, einst unsterblich und verehrt, sich schwer tut, sich selbst in dem bescheidenen Licht zu sehen, das uns wahrscheinlich gebührt. Wir müssen uns unserer Verbindung mit der Natur und mit Elune gewahr werden und unsere sterblichen Fehler hinter uns lassen.",CompletedText_loc3="" WHERE Id=929;

-- quest 933
UPDATE locales_quest SET Title_loc3="Teldrassil: Der Anbruch des Tages",Details_loc3="Ich möchte, dass Ihr noch einen letzten Mondbrunnen besucht. Er liegt direkt südlich von hier am Ufer der Teiche von Arlithrien. Seid vorsichtig, wenn Ihr Euch dem Brunnen nähert und haltet Eure Waffen bereit. Ich verspüre eine wachsende Verderbnis von den südlichen Ästen Teldrassils her.$B$BSobald Ihr das Wasser habt, möchte ich, dass Ihr es zu einem vertrauten Gesicht bringt, dem Ihr dort an den Teichen begegnen werdet. Sie möchte die Verderbnis bekämpfen und hat nach Euch persönlich gefragt.",OfferRewardText_loc3="Ich habe in der Tat auf meinem Weg hierher mit Corithras gesprochen und er hat mir das Wasser, das Ihr gesammelt habt, zur Verfügung gestellt. Es könnte sich sehr wohl noch als nützlich erweisen, und zwar früher als wir dachten.$B$BMerkwürdigerweise ist die wachsende Verderbnis, die wir verspürt haben, in Wahrheit ein gutes Zeichen. Teldrassil ist schon seit langer Zeit mit dieser Verunreinigung belastet und dank des Segens der Drachenaspekte tritt sie nun in einer Form ans Tageslicht, gegen die wir etwas ausrichten können.",RequestItemsText_loc3="Es ist schön, Euch wiederzusehen, $N. Wie ich sehe, habt Ihr erfolgreich das Wasser der Mondbrunnen für Corithras Mondzorn gesammelt. Ich hoffe, Ihr habt währenddessen viel gelernt.",CompletedText_loc3="" WHERE Id=933;

-- quest 935
UPDATE locales_quest SET Title_loc3="Die Wasser von Teldrassil",Objectives_loc3="Bringt das gefüllte Gefäß zu Corithras Mondzorn an der Kreuzung vor Darnassus.",Details_loc3="Unsere Arbeit ist hier fürs Erste getan. Dieses Wasser hat sich als sehr bedeutsam herausgestellt, doch war es ursprünglich nicht für mich bestimmt. Geht nur und bringt es zu Corithras an der Wegkreuzung. Ich bin mir sicher, er möchte gern, dass Ihr es an seinen eigentlichen Bestimmungsort bringt.",OfferRewardText_loc3="Danke, dass Ihr so schnell zu mir zurückgekehrt seid. Ich muss Euch nur um einen letzten Dienst bitten. Wollen wir?",RequestItemsText_loc3="Es ist schön, Euch wiederzusehen. Ich spüre, dass Tarindrellas Aufgabe mit Euch an ihrer Seite reibungslos verlaufen ist." WHERE Id=935;

-- quest 7383
UPDATE locales_quest SET Title_loc3="Teldrassil: Die Bürde der Kaldorei",Objectives_loc3="Füllt die Amethystphiole.",Details_loc3="Ihr müsst nun den Mondbrunnen unter den Ästen des Orakelbaums im fernen Nordwesten aufsuchen. Er ist der erste und mächtigste unserer Brunnen und es heißt von seinem Wasser, es enthalte die Essenz von Elunes Macht. Entnehmt eine Phiole des Wassers und kehrt zu mir zurück. Ich werde euch an der Weggabelung vor Darnassus treffen, wenn Eure Aufgabe vollendet ist.",CompletedText_loc3="" WHERE Id=7383;

-- quest 6341
UPDATE locales_quest SET Title_loc3="Auf nach Darnassus",Objectives_loc3="Sprecht mit Fidelio, um einen Flug nach Darnassus zu erstehen, und bringt dann die Rezeptsammlung von Dolanaar zu Schwester Aquinne in Darnassus.",Details_loc3="Alle in Dolanaar sind so stolz auf Schwester Aquinne. Ich bin sicher, sie wird sich sehr freuen, dieses aufmerksame Geschenk von Nyoma zu erhalten.$B$BWenn Ihr bereit seid, nach Darnassus zu reisen, sprecht einfach wieder mit mir und für ein paar Münzen könnt Ihr einen Hippogryphen mieten, der Euch dorthin bringt. Man sagte mir, Schwester Aquinne genießt die Abgeschiedenheit eines kleinen Platzes südlich vom Hippogryphenmeister in Darnassus. Sucht dort nach ihr, wenn Ihr angekommen seid.",RequestItemsText_loc3="Wie kann ich Euch helfen?" WHERE Id=6341;

-- quest 6344
UPDATE locales_quest SET Title_loc3="Andenken an Zuhause",Objectives_loc3="Bringt die Rezeptsammlung von Dolanaar zu Fidelio in Dolanaar.",Details_loc3="Eine Freundin von mir, Schwester Aquinne, ist in der Ausbildung zur Mondpriesterin in Darnassus. Sie hat Dolanaar letztes Jahr verlassen, um im Tempel zu lernen. Laut ihren Briefen geht es ihr gut und sie lernt viel, aber sie vermisst ihr Zuhause und ihre alten Freunde. Ich habe ein Buch mit ihren Lieblingsrezepten aus Dolanaar zusammengestellt.$B$BWenn Ihr die Zeit findet, könntet Ihr es ihr nach Darnassus bringen? Ihr könnt einen Hippogryphen von Fidelio mieten. Er befindet sich in der Mitte der Stadt, gegenüber vom Gasthaus.",OfferRewardText_loc3="Das ist sehr aufmerksam von Nyoma. Für ein paar Münzen kann ich Euch mit einem meiner Hippogryphen ein schnelles Transportmittel in die Hauptstadt zur Verfügung stellen." WHERE Id=6344;

-- quest 6342
UPDATE locales_quest SET Title_loc3="Ein unerwartetes Geschenk",Objectives_loc3="Bringt Schwester Aquinnes Notiz zu Leora, der Hippogryphenmeisterin in Darnassus.",Details_loc3="Das ist wundervoll! Genau das Richtige, um mich während meiner Studien im Tempel des Mondes an mein Zuhause zu erinnern. Ich werde eins der Rezepte heute Abend ausprobieren. Ich kann es kaum abwarten!$B$BWürdet Ihr diese kurze Dankesnachricht zu Nyoma zurückbringen? Ihr könnt einen Hippogryphen zurück nach Dolanaar mieten. Besucht einfach unsere Hippogryphenmeisterin, Leora, wenn Ihr zum Abflug bereit seid. Sie wird Euch mit einem Rückflug nach Dolanaar helfen.",OfferRewardText_loc3="Braucht Ihr einen Flug zurück nach Dolanaar?",RequestItemsText_loc3="Seid Ihr bereit, nach Dolanaar zurückzukehren?" WHERE Id=6342;

-- quest 6343
UPDATE locales_quest SET Title_loc3="Rückkehr zu Nyoma",Objectives_loc3="Sprecht mit Leora, um einen Hippogryphen zu mieten, der Euch nach Dolanaar zurückbringt. Sobald Ihr in Dolanaar angekommen seid, bringt Schwester Aquinnes Nachricht zu Nyoma.",Details_loc3="Euch einen Flug zurück nach Dolanaar zu besorgen, wird einfach sein. Da Ihr Fidelio in Dolanaar bereits kennt, könnt Ihr ohne Probleme dorthin zurückfliegen.$B$BImmer wenn Ihr in einer neuen Stadt ankommt, solltet Ihr daran denken, mit dem Flugmeister zu sprechen, damit Ihr zu und von diesem neuen Ort fliegen könnt.$B$BSprecht mit mir, wenn Ihr bereit seid, einen Hippogryphen für den Rückflug nach Dolanaar zu mieten.",OfferRewardText_loc3="Es klingt, als hätte es ihr sehr gefallen. Danke, dass Ihr das Buch zu Schwester Aquinne gebracht habt, <Name>. Irgendwann bald werde ich ihre Einladung annehmen und sie in Darnassus besuchen.",RequestItemsText_loc3="$N, Ihr seid aus Darnassus zurück?" WHERE Id=6343;

-- quest 13945
UPDATE locales_quest SET QuestGiverTextWindow_loc3="Verteidiger der Knarzklauen auf dem Grabhügel von Ban'ethil",QuestGiverTargetName_loc3="Verteidiger der Knarzklauen" WHERE Id=13945;




